export enum ExceptionMessageCode {
    // generals
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    GENERAL_ERROR = 'GENERAL_ERROR',

    // token errors
    TOKEN_ERROR = 'TOKEN_ERROR',
    TOKEN_NOT_BEFORE_ERROR = 'TOKEN_NOT_BEFORE_ERROR',
    TOKEN_EXPIRED_ERROR = 'TOKEN_EXPIRED_ERROR',
    TOKEN_MISSING = 'TOKEN_MISSING',
    TOKEN_PAYLOAD_MISSING = 'TOKEN_PAYLOAD_MISSING',
    TOKEN_PARAMETER_MISSING = 'TOKEN_PARAMETER_MISSING',
    TOKEN_MISMATCH_ERROR = 'TOKEN_MISMATCH_ERROR',

    ACCESS_TOKEN_MISSING = 'ACCESS_TOKEN_MISSING',
    REFRESH_TOKEN_MISSING = 'REFRESH_TOKEN_MISSING',
    FORGOT_PASSWORD_TOKEN_MISSING = 'FORGOT_PASSWORD_TOKEN_MISSING',

    // others
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    USER_EMAIL_OR_PASSWORD_INCORRECT = 'USER_EMAIL_OR_PASSWORD_INCORRECT',
    USER_EMAIL_ALREADY_IN_USE = 'USER_EMAIL_ALREADY_IN_USE',
    USER_ALREADY_IN_CACHE = 'USER_ALREADY_IN_CACHE',
    USERNAME_ALREADY_IN_USE = 'USERNAME_ALREADY_IN_USE',

    ONLY_JPEG_ALLOWED='ONLY_JPEG_ALLOWED',

    INCORRECT_UUID = 'INCORRECT_UUID',
}
